# Install a more up to date mongodb than what is included in the default ubuntu repositories.

FROM mongo:6.0.5-jammy
MAINTAINER Tom Johander

#RUN echo "" >> /etc/mongodb.conf

CMD ["/usr/bin/mongod", "--config", "/etc/mongodb.conf"] 
